version: '3.8'

services:

  dataDD:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${DATABASE_NAME:?}
      MYSQL_USER: ${DATABASE_USER:?}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?}
    ports:
      - ${DATABASE_PORT:-3306}:3306
    volumes:
      - /data/db:/var/lib/mysql
      - "./data:/docker-entrypoint-initdb.d"
    restart: always

  backendDD:
    image: dd_backend
    build:
      context: ./backend
    depends_on:
      - dataDD
    environment:
      DATABASE_HOST: dataDD
      DATABASE_NAME: ${DATABASE_NAME:?}
      DATABASE_USER: ${DATABASE_USER:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      DATABASE_PORT: 3306
      PORT_TO_SHOW: ${BACKEND_PORT:?}
    ports:
      - ${BACKEND_PORT:?}:80

  frontendDD:
    image: dd_frontend
    build:
      context: ./frontend
    environment:
      - BACKEND
    ports:
      - ${FRONTEND_PORT:?}:80